os:
  - linux
  - osx
language: c
compiler:
  - clang
  - gcc
sudo: required
dist: trusty
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
addons:
  coverity_scan:
    project:
      name: "kala13x/libxutils"
    notification_email: sundro.kala@gmail.com
    branch_pattern: coverity_scan
