version: 2.1

jobs:
  "build":
    docker:
      - image: "cimg/base:2022.03"
    steps:
      - checkout
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install deps
          command: 'sudo apt-get update && sudo apt-get install -y libssl-dev'
      - run:
          name: Check versions
          command: |
            gcc --version
            cmake --version
      - run:
          name: Make build
          command: |
            mkdir build
            cd build
            cmake ..
            cd ..
            make

workflows:
  version: 2.1
  build:
    jobs:
      - "build"