name: Build libxutils project

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Install CMAKE
        run: sudo apt install -y cmake

      - name: Install dependencies
        run: sudo apt install -y libssl-dev

      - name: Check versions
        run: |
          gcc --version
          cmake --version

      - name: Make build
        run: |
          mkdir build
          cd build
          cmake ..
          make
