name: Full Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libssl-dev

    - name: Install CMAKE
      run: sudo apt install -y cmake

    - name: Checkout SMAKE
      uses: actions/checkout@v3
      with:
        repository: 'kala13x/smake'
        submodules: recursive
        path: 'smake'

    - name: Install SMAKE
      run: cd smake && ./build.sh --install

    - name: Build with SMAKE (SSL)
      run: ./build.sh smake

    - name: Build with SMAKE (no SSL)
      run: ./build.sh smake --ssl=no

    - name: Build with CMAKE (SSL)
      run: ./build.sh cmake
      
    - name: Build with CMAKE (no SSL)
      run: ./build.sh cmake --ssl=no
      
    - name: Build with Makefile (SSL)
      run: ./build.sh make

    - name: Build with Makefile (no SSL)
      run: ./build.sh make --ssl=no
